apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml

namespace: crud-logger

images:
- name: imagem
  newName: blgianini/crud-logger
  newTag: 64512abd52b05ffaa62f5b7bb4d1515d2aa44d1f
